Repository Dining-together/Frontend, pull requests merged in 2021-08, with the labels that each got.

#51 공고 조회 서버 연동 및 정렬 기능
  src/navigations/MypageStack.js
  src/screens/Account/AccountFind.js
  src/screens/Account/Login.js
  src/screens/Account/Mode.js
  src/screens/Account/Signup.js
  src/screens/Auction.js
  src/screens/AuctionBid.js
  src/screens/AuctionDetail.js
  src/screens/AuctionFinished.js
  src/screens/DocumentRegister.js
  src/screens/Main.js
  src/screens/MyPage/BidManage.js
  src/screens/MyPage/BidManageFinished.js
  src/screens/MyPage/Bookmark.js
  src/screens/MyPage/ChatManage.js
  src/screens/MyPage/DocumentRegister.js
  src/screens/MyPage/MultipleImage.js
  src/screens/MyPage/MyPage_User.js
  src/screens/MyPage/Mypage_Store.js
  src/screens/MyPage/OrderDetail.js
  src/screens/MyPage/PayManage.js
  src/screens/MyPage/ReviewManage.js
  src/screens/MyPage/ReviewWrite.js
  src/screens/MyPage/StoreBasicChange.js
  src/screens/MyPage/StoreConvChange.js
  src/screens/MyPage/StoreInfo.js
  src/screens/MyPage/StoreInfoChange.js
  src/screens/MyPage/StoreManage.js
  src/screens/MyPage/UseManage.js
  src/screens/MyPage/UserInfo.js
  src/screens/MyPage/UserInfoChange.js
  src/screens/RegisterAuction.js
  src/screens/Store.js
  src/screens/StoreConvChange.js
  src/screens/StoreInfo.js
  src/screens/StoreInfoChange.js
  src/screens/StoreManage.js
  src/screens/index.js
  src/utils/regionData.js
Labels: status : 리뷰요청

#57 [Fix] Review InfoChange and StoreMange
  src/components/Image.js
  src/components/Input.js
  src/components/ProfileImage.js
  src/contexts/LoginSuccess.js
  src/navigations/StoreListTab.js
  src/screens/Account/Login.js
  src/screens/Account/Signup.js
  src/screens/Main.js
  src/screens/MyPage/DocumentRegister.js
  src/screens/MyPage/MyPage_User.js
  src/screens/MyPage/Mypage_Store.js
  src/screens/MyPage/StoreBasicChange.js
  src/screens/MyPage/StoreConvChange.js
  src/screens/MyPage/StoreInfo.js
  src/screens/MyPage/StoreManage.js
  src/screens/MyPage/UserInfo.js
  src/screens/MyPage/UserInfoChange.js
  src/screens/RegisterAuction.js
  src/screens/StoreDetail.js
  src/screens/StoreList/AllStore.js
  src/screens/StoreList/ChStore.js
  src/screens/StoreList/EtcStore.js
  src/screens/StoreList/JpStore.js
  src/screens/StoreList/KrStore.js
  src/screens/StoreList/WsStore.js
  src/screens/index.js
  src/utils/common.js
Labels: status : 리뷰요청

#61 [Feat] Add Store Map API
  src/components/ProfileImage.js
  src/contexts/LoginSuccess.js
  src/contexts/Url.js
  src/screens/Account/AccountFind.js
  src/screens/Account/Login.js
  src/screens/Auction.js
  src/screens/AuctionBid.js
  src/screens/AuctionDetail.js
  src/screens/AuctionFinished.js
  src/screens/Main.js
  src/screens/MyPage/Mypage_Store.js
  src/screens/MyPage/StoreManage.js
  src/screens/OnlyCustomer.js
  src/screens/RegisterAuction.js
  src/screens/StoreDetail.js
  src/screens/StoreList/AllStore.js
  src/screens/StoreList/ChStore.js
  src/screens/StoreList/EtcStore.js
  src/screens/StoreList/JpStore.js
  src/screens/StoreList/KrStore.js
  src/screens/StoreList/StoreMap.js
  src/screens/StoreList/WsStore.js
  src/screens/StoreMap.js
  src/screens/index.js
  src/utils/regionData.js
Labels: status : 리뷰요청

#66 [Feat] 입찰 및 낙찰 구현
  assets/android-icon.png
  assets/icon.png
  assets/splash.png
  src/navigations/AuctionDetailStack.js
  src/navigations/LogManageTab.js
  src/navigations/MypageStack.js
  src/navigations/RegisterAuctionStack.js
  src/navigations/SearchAuctionStack.js
  src/navigations/SearchStoreStack.js
  src/navigations/SearchTab.js
  src/screens/Account/Signup.js
  src/screens/Auction.js
  src/screens/AuctionBidDetail.js
  src/screens/AuctionDetail.js
  src/screens/AuctionFinished.js
  src/screens/Main.js
  src/screens/MyPage/AucLogManage.js
  src/screens/MyPage/BidLogManage.js
  src/screens/MyPage/BidManage.js
  src/screens/MyPage/BidManageFinished.js
  src/screens/MyPage/Bookmark.js
  src/screens/MyPage/LogManage.js
  src/screens/MyPage/MyPage_User.js
  src/screens/MyPage/Mypage_Store.js
  src/screens/MyPage/ReviewManage.js
  src/screens/MyPage/ReviewWrite.js
  src/screens/MyPage/StoreBasicChange.js
  src/screens/MyPage/StoreManage.js
  src/screens/MyPage/UseManage.js
  src/screens/RegisterAuction.js
  src/screens/Review.js
  src/screens/SearchAuction.js
  src/screens/SearchStore.js
  src/screens/StoreDetail.js
  src/screens/StoreList/AllStore.js
  src/screens/StoreList/ChStore.js
  src/screens/StoreList/EtcStore.js
  src/screens/StoreList/JpStore.js
  src/screens/StoreList/KrStore.js
  src/screens/StoreList/StoreMap.js
  src/screens/StoreList/WsStore.js
  src/screens/index.js
  src/utils/common.js
Labels: status : 진행중 ✊, status : 테스트

#67 사용자 이용관리 & 리뷰관리
  src/contexts/LoginSuccess.js
  src/contexts/Url.js
  src/navigations/LogManageTab.js
  src/navigations/MypageStack.js
  src/navigations/RegisterAuctionStack.js
  src/screens/Account/Login.js
  src/screens/Account/Signup.js
  src/screens/Auction.js
  src/screens/AuctionBid.js
  src/screens/AuctionDetail.js
  src/screens/AuctionFinished.js
  src/screens/Main.js
  src/screens/MyPage/AucLogManage.js
  src/screens/MyPage/BidLogManage.js
  src/screens/MyPage/BidManage.js
  src/screens/MyPage/BidManageFinished.js
  src/screens/MyPage/Bookmark.js
  src/screens/MyPage/LogManage.js
  src/screens/MyPage/Mypage_Store.js
  src/screens/MyPage/ReviewManage.js
  src/screens/MyPage/ReviewWrite.js
  src/screens/MyPage/StoreBasicChange.js
  src/screens/MyPage/StoreManage.js
  src/screens/MyPage/UseManage.js
  src/screens/OnlyCustomer.js
  src/screens/RegisterAuction.js
  src/screens/StoreDetail.js
  src/screens/StoreList/AllStore.js
  src/utils/common.js
  src/utils/regionData.js
Labels: status : 진행중 ✊
